### ISSUE TITLE
Can't create plugin

### ISSUE THREAD

**Issue by RoganDawes** [doyensec/wsrepl#2]
I tried to create a basic plugin to base64-code the messages, but I just got Python exceptions.

I based it on your "Customizing the REPL UI" example at https://blog.doyensec.com/2023/07/18/streamlining-websocket-pentesting-with-wsrepl.html:

```
from wsrepl import Plugin
import base64

import json
from wsrepl.WSMessage import WSMessage

class Demo(Plugin):
    async def on_message_sent(self, message: WSMessage) -> None:
        original = message.msg
        message.msg = base64.b64encode(original)
        message.short = original
        message.long = message.msg

    async def on_message_received(self, message: WSMessage) -> None:
        original = message.msg

        try:
            message.short = base64.b64decode(original)
        except:
            message.short = "Error: could not parse message"

        message.long = original
```
The first exception I got was:
```
  File "/opt/homebrew/lib/python3.11/site-packages/wsrepl/utils.py", line 99, in load_plugin
    spec = importlib.util.spec_from_file_location(plugin_name, plugin_path)
           ^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'util'
```
Apparently the solution to that is to `import importlib.util`, so I added that in `utils.py`.
Then I got:
```
  File "/opt/homebrew/lib/python3.11/site-packages/wsrepl/utils.py", line 101, in load_plugin
    module = importlib.util.module_from_spec(spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 570, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```
But I have no idea how to solve that.

**Comment by execveat** [comment]
Hi @RoganDawes, thank you for a bug report! Could you please help me replicate it? It looks like you're on a Mac and using Python 3.11 installed through Homebrew, but this setup actually works fine for me.

Could you please run `python` from the `wsrepl` directory and try to run the same code there?

```python
import importlib
spec = importlib.util.spec_from_file_location('math', 'docs/demo-1.py')
importlib.util.module_from_spec(spec)
```

Please, just copy the whole output here for debugging. If it produces an error, try the second approach with `importlib.util`:

```python
import importlib.util
spec = importlib.util.spec_from_file_location('math', 'docs/demo-1.py')
importlib.util.module_from_spec(spec)
```

**Comment by RoganDawes** [comment]
Ok, I tried working from the github repo - uninstalled wsrepl using `pip3 uninstall wsrepl`, then cloned, made a venv, activated it, and `pip install .` Yes, I'm using a Mac (M1), with homebrew:
```
/Users/rogan/workspace/wsrepl/venv/bin/python3.11 -> /opt/homebrew/opt/python@3.11/bin/python3.11
```
```
$ python -V
Python 3.11.3
```
This is what I get:
```
$ wsrepl -P base64.wsrepl wss://<redacted>
Traceback (most recent call last):
  File "/Users/rogan/workspace/wsrepl/venv/bin/wsrepl", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/rogan/workspace/wsrepl/venv/lib/python3.11/site-packages/wsrepl/cli.py", line 49, in cli
    app = WSRepl(
          ^^^^^^^
  File "/Users/rogan/workspace/wsrepl/venv/lib/python3.11/site-packages/wsrepl/app.py", line 58, in __init__
    self.message_handler = MessageHandler(
                           ^^^^^^^^^^^^^^^
  File "/Users/rogan/workspace/wsrepl/venv/lib/python3.11/site-packages/wsrepl/MessageHandler.py", line 38, in __init__
    self.plugin = load_plugin(plugin_path)(message_handler=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rogan/workspace/wsrepl/venv/lib/python3.11/site-packages/wsrepl/utils.py", line 99, in load_plugin
    spec = importlib.util.spec_from_file_location(plugin_name, plugin_path)
           ^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'util'
```
Edited `/Users/rogan/workspace/wsrepl/venv/lib/python3.11/site-packages/wsrepl/utils.py` to add `import importlib.util`, and now I get:
```
$ wsrepl -P base64.wsrepl wss://<redacted>
Traceback (most recent call last):
  File "/Users/rogan/workspace/wsrepl/venv/bin/wsrepl", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/rogan/workspace/wsrepl/venv/lib/python3.11/site-packages/wsrepl/cli.py", line 49, in cli
    app = WSRepl(
          ^^^^^^^
  File "/Users/rogan/workspace/wsrepl/venv/lib/python3.11/site-packages/wsrepl/app.py", line 58, in __init__
    self.message_handler = MessageHandler(
                           ^^^^^^^^^^^^^^^
  File "/Users/rogan/workspace/wsrepl/venv/lib/python3.11/site-packages/wsrepl/MessageHandler.py", line 38, in __init__
    self.plugin = load_plugin(plugin_path)(message_handler=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rogan/workspace/wsrepl/venv/lib/python3.11/site-packages/wsrepl/utils.py", line 101, in load_plugin
    module = importlib.util.module_from_spec(spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 570, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

**Comment by execveat** [comment]
Thank you, I've replicated the error. Freshly compiled Python doesn't have this issue, so I'll need some time to investigate what's special about the version Homebrew installs.

**Comment by execveat** [comment]
Turned out to be pretty straightforward actually. The error message coming from importlib was very misleading, so I added an explicit check for the existence of the plugin on the file system.

Also, use `pip install -e .` if you want to edit files and see the effect without explicitly running `pip install .` again.

I think this commit should cover your case, please reopen it if you're still seeing an error.

**Comment by josephwhenry** [comment]
@execveat It seems that the package that `pip` downloads is still susceptible to this issue. I tried `pip install wsrepl` and wound up here. Uninstalling and then reinstalling from source code fixed the issue.
